/* Generated By:JavaCC: Do not edit this line. RustGrammarConstants.java */
package compiladores;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RustGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT_BLOCK = 5;
  /** RegularExpression Id. */
  int COMMENT_LINE = 6;
  /** RegularExpression Id. */
  int USE = 7;
  /** RegularExpression Id. */
  int FN = 8;
  /** RegularExpression Id. */
  int LET = 9;
  /** RegularExpression Id. */
  int MUT = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int FOR = 13;
  /** RegularExpression Id. */
  int IN = 14;
  /** RegularExpression Id. */
  int RANGE_OP = 15;
  /** RegularExpression Id. */
  int PRINTLN = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int INTEGER = 18;
  /** RegularExpression Id. */
  int STRING = 19;
  /** RegularExpression Id. */
  int COLON = 20;
  /** RegularExpression Id. */
  int SEMICOLON = 21;
  /** RegularExpression Id. */
  int COMMA = 22;
  /** RegularExpression Id. */
  int LPAREN = 23;
  /** RegularExpression Id. */
  int RPAREN = 24;
  /** RegularExpression Id. */
  int LBRACE = 25;
  /** RegularExpression Id. */
  int RBRACE = 26;
  /** RegularExpression Id. */
  int PLUS = 27;
  /** RegularExpression Id. */
  int MOD = 28;
  /** RegularExpression Id. */
  int ASSIGN = 29;
  /** RegularExpression Id. */
  int DOT = 30;
  /** RegularExpression Id. */
  int NOT = 31;
  /** RegularExpression Id. */
  int ARROW = 32;
  /** RegularExpression Id. */
  int LT = 33;
  /** RegularExpression Id. */
  int GT = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT_BLOCK>",
    "<COMMENT_LINE>",
    "\"use\"",
    "\"fn\"",
    "\"let\"",
    "\"mut\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"in\"",
    "\"..\"",
    "\"println!\"",
    "<IDENTIFIER>",
    "<INTEGER>",
    "<STRING>",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"%\"",
    "\"=\"",
    "\".\"",
    "\"!\"",
    "\"->\"",
    "\"<\"",
    "\">\"",
    "\"i32\"",
    "\"String\"",
  };

}
