/* Generated By:JavaCC: Do not edit this line. RustParserConstants.java */
package compiladores;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RustParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int IF = 4;
  /** RegularExpression Id. */
  int ELSE = 5;
  /** RegularExpression Id. */
  int FN = 6;
  /** RegularExpression Id. */
  int LET = 7;
  /** RegularExpression Id. */
  int MUT = 8;
  /** RegularExpression Id. */
  int PRINTLN = 9;
  /** RegularExpression Id. */
  int RETURN = 10;
  /** RegularExpression Id. */
  int PUB = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int LOOP = 14;
  /** RegularExpression Id. */
  int I32_TYPE = 15;
  /** RegularExpression Id. */
  int F64_TYPE = 16;
  /** RegularExpression Id. */
  int BOOL_TYPE = 17;
  /** RegularExpression Id. */
  int STRING_TYPE = 18;
  /** RegularExpression Id. */
  int EQ = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int STAR = 22;
  /** RegularExpression Id. */
  int SLASH = 23;
  /** RegularExpression Id. */
  int PERCENT = 24;
  /** RegularExpression Id. */
  int GT = 25;
  /** RegularExpression Id. */
  int LT = 26;
  /** RegularExpression Id. */
  int GE = 27;
  /** RegularExpression Id. */
  int LE = 28;
  /** RegularExpression Id. */
  int EQ_EQ = 29;
  /** RegularExpression Id. */
  int NE = 30;
  /** RegularExpression Id. */
  int SEMICOLON = 31;
  /** RegularExpression Id. */
  int COLON = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int LBRACE = 34;
  /** RegularExpression Id. */
  int RBRACE = 35;
  /** RegularExpression Id. */
  int LPAREN = 36;
  /** RegularExpression Id. */
  int RPAREN = 37;
  /** RegularExpression Id. */
  int LBRACKET = 38;
  /** RegularExpression Id. */
  int RBRACKET = 39;
  /** RegularExpression Id. */
  int EXCLAMATION = 40;
  /** RegularExpression Id. */
  int AMPERSAND = 41;
  /** RegularExpression Id. */
  int DOT = 42;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 43;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 44;
  /** RegularExpression Id. */
  int STRING_LITERAL = 45;
  /** RegularExpression Id. */
  int TRUE = 46;
  /** RegularExpression Id. */
  int FALSE = 47;
  /** RegularExpression Id. */
  int IDENTIFIER = 48;
  /** RegularExpression Id. */
  int LETTER = 49;
  /** RegularExpression Id. */
  int DIGIT = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"if\"",
    "\"else\"",
    "\"fn\"",
    "\"let\"",
    "\"mut\"",
    "\"println!\"",
    "\"return\"",
    "\"pub\"",
    "\"for\"",
    "\"while\"",
    "\"loop\"",
    "\"i32\"",
    "\"f64\"",
    "\"bool\"",
    "\"String\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"!\"",
    "\"&\"",
    "\".\"",
    "<INTEGER_LITERAL>",
    "<FLOAT_LITERAL>",
    "<STRING_LITERAL>",
    "\"true\"",
    "\"false\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
