/* Generated By:JavaCC: Do not edit this line. RustGrammarConstants.java */
package compiladorRust;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RustGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_SIMPLES = 6;
  /** RegularExpression Id. */
  int COMENTARIO_LONGO = 7;
  /** RegularExpression Id. */
  int FN = 8;
  /** RegularExpression Id. */
  int MAIN = 9;
  /** RegularExpression Id. */
  int LET = 10;
  /** RegularExpression Id. */
  int MUT = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int ELSE_IF = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int PRINT = 18;
  /** RegularExpression Id. */
  int PRINTLN = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int USE = 21;
  /** RegularExpression Id. */
  int READLINE = 22;
  /** RegularExpression Id. */
  int BREAK = 23;
  /** RegularExpression Id. */
  int CONTINUE = 24;
  /** RegularExpression Id. */
  int I8 = 25;
  /** RegularExpression Id. */
  int I16 = 26;
  /** RegularExpression Id. */
  int I32 = 27;
  /** RegularExpression Id. */
  int I64 = 28;
  /** RegularExpression Id. */
  int U8 = 29;
  /** RegularExpression Id. */
  int U16 = 30;
  /** RegularExpression Id. */
  int U32 = 31;
  /** RegularExpression Id. */
  int U64 = 32;
  /** RegularExpression Id. */
  int F32 = 33;
  /** RegularExpression Id. */
  int F64 = 34;
  /** RegularExpression Id. */
  int BOOL_TYPE = 35;
  /** RegularExpression Id. */
  int CHAR_TYPE = 36;
  /** RegularExpression Id. */
  int STRING_TYPE = 37;
  /** RegularExpression Id. */
  int ABRE_CHAVES = 38;
  /** RegularExpression Id. */
  int FECHA_CHAVES = 39;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 40;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 41;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 42;
  /** RegularExpression Id. */
  int VIRGULA = 43;
  /** RegularExpression Id. */
  int DOIS_PONTOS = 44;
  /** RegularExpression Id. */
  int SETA = 45;
  /** RegularExpression Id. */
  int PONTO = 46;
  /** RegularExpression Id. */
  int IGUAL = 47;
  /** RegularExpression Id. */
  int MAIS = 48;
  /** RegularExpression Id. */
  int MENOS = 49;
  /** RegularExpression Id. */
  int ASTERISCO = 50;
  /** RegularExpression Id. */
  int BARRA = 51;
  /** RegularExpression Id. */
  int PORCENTAGEM = 52;
  /** RegularExpression Id. */
  int E_LOGICO = 53;
  /** RegularExpression Id. */
  int OU_LOGICO = 54;
  /** RegularExpression Id. */
  int NEGACAO = 55;
  /** RegularExpression Id. */
  int DUPLO_IGUAL = 56;
  /** RegularExpression Id. */
  int DIFERENTE = 57;
  /** RegularExpression Id. */
  int MAIOR = 58;
  /** RegularExpression Id. */
  int MENOR = 59;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 60;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 61;
  /** RegularExpression Id. */
  int MAIS_IGUAL = 62;
  /** RegularExpression Id. */
  int MENOS_IGUAL = 63;
  /** RegularExpression Id. */
  int ASTERISCO_IGUAL = 64;
  /** RegularExpression Id. */
  int BARRA_IGUAL = 65;
  /** RegularExpression Id. */
  int PORCENTAGEM_IGUAL = 66;
  /** RegularExpression Id. */
  int DUPLO_DOIS_PONTOS = 67;
  /** RegularExpression Id. */
  int E_COMERCIAL = 68;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 69;
  /** RegularExpression Id. */
  int LETRA = 70;
  /** RegularExpression Id. */
  int DIGITO = 71;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 72;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 73;
  /** RegularExpression Id. */
  int STRING_LITERAL = 74;
  /** RegularExpression Id. */
  int BOOL_LITERAL = 75;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<COMENTARIO_SIMPLES>",
    "<COMENTARIO_LONGO>",
    "\"fn\"",
    "\"main\"",
    "\"let\"",
    "\"mut\"",
    "\"if\"",
    "\"else if\"",
    "\"else\"",
    "\"while\"",
    "\"true\"",
    "\"false\"",
    "\"print!\"",
    "\"println!\"",
    "\"return\"",
    "\"use\"",
    "\"read_line\"",
    "\"break\"",
    "\"continue\"",
    "\"i8\"",
    "\"i16\"",
    "\"i32\"",
    "\"i64\"",
    "\"u8\"",
    "\"u16\"",
    "\"u32\"",
    "\"u64\"",
    "\"f32\"",
    "\"f64\"",
    "\"bool\"",
    "\"char\"",
    "\"String\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\"->\"",
    "\".\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"::\"",
    "\"&\"",
    "<IDENTIFICADOR>",
    "<LETRA>",
    "<DIGITO>",
    "<INTEGER_LITERAL>",
    "<FLOAT_LITERAL>",
    "<STRING_LITERAL>",
    "<BOOL_LITERAL>",
  };

}
